server:
  port: 7002
  servlet:
    session.timeout: 300

logging:
  level:
    #日志优先级（只会输出指定优先级及以上的日志信息）
    org.springframework.web: debug
    cn.cloud: debug
#  file: logs/kafka-websocket.log

spring:
  #Druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rbac_db?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root

  # 内网redis
  redis:
    host: 192.168.3.60
    port: 6381
    timeout: 20000
    database: 2
    password: Yuhan123456
    sentinel:
      master: mymaster
      nodes: 192.168.3.60:26379,192.168.3.167:26379,192.168.3.168:26379
    #自定义的监听的TOPIC路径
    message:
      channel: websocket-channel
#mybatis
mybatis:
  type-aliases-package: cn.cloud.websocket.mapper
  mapper-locations: classpath:cn/cloud/websocket/mapper/xml/*.xml
